
export const APPWRITE_ENDPOINT = import.meta.env.VITE_APPWRITE_ENDPOINT;
export const APPWRITE_PROJECT = import.meta.env.VITE_APPWRITE_PROJECT;
export const APPWRITE_DEV_KEY = import.meta.env.VITE_APPWRITE_DEV_KEY;
export const APPWRITE_DATABASE_ID = import.meta.env.VITE_APPWRITE_DATABASE_ID;
export const APPWRITE_STORAGE_ID = import.meta.env.VITE_APPWRITE_STORAGE_ID;

// Collection 
export const APPWRITE_EVENTS_TABLE_ID = import.meta.env.VITE_APPWRITE_EVENTS_TABLE_ID;
export const APPWRITE_REGISTERATION_TABLE_ID = import.meta.env.VITE_APPWRITE_REGISTERATION_TABLE_ID;
export const APPWRITE_MESSAGE_TABLE_ID = import.meta.env.VITE_APPWRITE_MESSAGE_TABLE_ID;
